### ISSUE TITLE
Improvement for dep

### ISSUE THREAD

**Issue by miladezzat** [khaledosama999/distributed-locks#2]
- you don't need these drivers on `dep` and make one of them as required when the user uses it 😄 
<img width="316" alt="Screenshot 2023-03-11 at 10 44 42 PM" src="https://user-images.githubusercontent.com/27713902/224510772-7e2a5a3e-e653-409c-a97c-d8d1ad8d9487.png">

**Comment by khaledosama999** [comment]
Done 
https://github.com/khaledosama999/distributed-locks/tree/master/.github/workflows
